DROP VIEW IF EXISTS sales;
DROP TABLE IF EXISTS staging;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS regions;
DROP TABLE IF EXISTS countries;
DROP TABLE IF EXISTS units;
DROP TABLE IF EXISTS sales_channels;
DROP TABLE IF EXISTS order_priorities;
